### ISSUE TITLE
Local build not rendering without newer version of eslint

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/contributor-spotlight#194]
### Reproduction steps

Fork the repository
Create a local clone
Follow the instructions in the repo readme to run the development environment
Results in:
![spotlight build error](https://github.com/user-attachments/assets/fdbca654-c22c-4b4f-98fe-0c317db49dd3)

In order to remedy this, I found this [thread/answer ](https://github.com/gatsbyjs/gatsby/issues/17557#issuecomment-908652439). After running `npm install eslint@latest --save-dev` the site was able to build and render as expected

Updated package-lock.json file: [package-lock.json](https://github.com/user-attachments/files/16944385/package-lock.json)
Updated package.json file: 
[package.json](https://github.com/user-attachments/files/16944408/package.json)

It appears that there were other updates in addition to the eslint version, but I'm not well versed enough to know whether they are all tied to eslint or if they are others that were pulled in.

### Expected Results

development environment builds and renders properly
![working development build](https://github.com/user-attachments/assets/487771de-2813-4352-8409-5bcda2b3caed)

### Actual Results

Error is thrown (as shown above in steps to reproduce) and the environment only renders the header & footer

### Anything else?

I think I ran into this issue when creating Olivier's spotlight but was able to build and render the page in deploy.

**Comment by kmartens27** [comment]
@krisstern am I potentially doing something wrong in my setup?

**Comment by krisstern** [comment]
@kmartens27 Sorry I missed this earlier... I think I might have fixed it. Is it still an issue?

**Comment by krisstern** [comment]
@kmartens27 Have you tried deleting the entire `node_modules` folder at the root and try running `npm i` again to install everything afresh?

**Comment by kmartens27** [comment]
I believe I might have during my research into what could be causing the issue, however I don't recall at this moment so let me try that out and see what happens.

**Comment by krisstern** [comment]
Sounds good! Do keep me posted

**Comment by krisstern** [comment]
Hi @kmartens27 that's good to know!

**Comment by kmartens27** [comment]
I believe this issue can be closed as the site is now building as expected
