### ISSUE TITLE
Add dark mode support similar to jenkins.io

### ISSUE THREAD

**Issue by krisstern** [jenkins-infra/contributor-spotlight#205]
### What feature do you want to see added?

We currently do not support dark mode on systems using the dark mode for the Contributor Spotlight, so would like this feature to be added similar to what we have at https://www.jenkins.io/ in https://github.com/jenkins-infra/jenkins.io in order to have a consistent dark-mode support accross all Jenkins site.

**Comment by etorres07** [comment]
@krisstern I'm going to take a look at this one. I skimmed through the jenkins.io repo and didn't see any obvious mention of dark mode. I will dig a bit deeper, but do you happen to have any pointers on where to start looking?

**Comment by krisstern** [comment]
Hey @etorres07, sure! Please keep us posted on any progress here. 

Also, you may use the following merged PR's as references:

1. Add dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7266
2. Fix some elements in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7457
3. Update back link icon in dark mode: https://github.com/jenkins-infra/jenkins.io/pull/7458
4. Refresh the design of the 'Changelogs' pages: https://github.com/jenkins-infra/jenkins.io/pull/7479

**Comment by Ashish-CodeJourney** [comment]
can you assign it to me ?

**Comment by krisstern** [comment]
Hi @Ashish-CodeJourney No, I cannot assign this ticket to you. @etorres07 is working on this.
