### ISSUE TITLE
Remove placeholder contributors

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/contributor-spotlight#21]
### What feature do you want to see added?

Placeholder contributors should be removed:

<img width="350" alt="image" src="https://github.com/jenkins-infra/contributor-spotlight/assets/91831478/ed8229b0-3ddf-4ea6-8514-409a5de83822">

A new one with a Jenkins Butler logo as avatar and a text with links and/or invitation to contribute could be a nice replacement, can be added in a second time.

**Comment by lemeurherve** [comment]
cc @jenkins-infra/contributor-spotlight

**Comment by kmartens27** [comment]
I have also created https://github.com/jenkins-infra/contributor-spotlight/pull/27 for removing the placeholder content entirely

**Comment by krisstern** [comment]
This has been done
