### ISSUE TITLE
Mobile view for contributors site not scaling properly

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/contributor-spotlight#29]
### What feature do you want to see added?

As pointed out in the [advocacy & outreach gitter channel](https://matrix.to/#/!cRulYWcErlSqXzBIyw:gitter.im/$I82WyoVWlFy2Q4el_UpSeVswSwS7EDhV4BrrWPi4WYE?via=gitter.im&via=matrix.org&via=g4v.dev), the mobile formatting of the contributor spotlight site could be improved. The feature box for the contributor seems to go off the page, and in the contributor page the text sticks to the center of the page.

![IMG_5846](https://github.com/jenkins-infra/contributor-spotlight/assets/99040580/5dcc9974-ab61-4273-81a5-193ce467c129)
![IMG_5847](https://github.com/jenkins-infra/contributor-spotlight/assets/99040580/4ba162e2-7a51-4ec2-ac29-ca3c87195580)

Would it be possible to update the mobile formatting so that the presentation is closer to the regular jenkins.io site?

**Comment by krisstern** [comment]
I will fix this later this week

**Comment by kmartens27** [comment]
No worries, thanks very much @krisstern!

**Comment by krisstern** [comment]
Hi @kmartens27 Job done in #32. It will look a lot nicer afterwards on mobile...
