### ISSUE TITLE
Add a `<title>` tag to the pages with the person's name e.g.

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/contributor-spotlight#37]
### What feature do you want to see added?

Without, it looks pretty weird:

![Screenshot 2023-11-30 at 18 25 22](https://github.com/jenkins-infra/contributor-spotlight/assets/13383509/9c34d134-52f7-4f18-9b5b-4f00d2ad71f5)

**Comment by krisstern** [comment]
We do have a title configured in the frontend currently: https://github.com/jenkins-infra/contributor-spotlight/blob/39b66028ea19b4da9f161d427019c97b59bcefdd/gatsby-config.js#L6. But that does not seem to be sufficient for our deployment setup to show the title.

**Comment by krisstern** [comment]
I will be working on a fix for this to be merged before the 2nd contributor feature goes out next / the coming Wednesday, following https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component.
