### ISSUE TITLE
Update Jenkins text logo navigation

### ISSUE THREAD

**Issue by kmartens27** [jenkins-infra/contributor-spotlight#42]
### What feature do you want to see added?

At this point in time, when someone clicks on the Jenkins text logo in the upper left hand corner, they will be brought to the contributors.jenkins.io home page. This is the same functionality as the plugins.jenkins.io page & stories.jenkins.io page, where if a user navigates to one of the plugin pages or a success story, and clicks on the Jenkins text logo, they are brought to the home page for that specific url/domain.

https://github.com/jenkins-infra/contributor-spotlight/assets/99040580/cf2c3871-687d-41b9-8375-8ed9bdaddb26

This could be confusing, as users may expect the Jenkins text logo to bring them directly to jenkins.io instead of the contributor home page or plugin home page. However, changing this may cause a chain reaction where the functionality is questioned on other pages.

Should this be updated or changed?

**Comment by krisstern** [comment]
Currently being discussed at https://github.com/jenkins-infra/jenkins-io-components/pull/118.
