### ISSUE TITLE
Fix missing opengraph metadata

### ISSUE THREAD

**Issue by NotMyFault** [jenkins-infra/contributor-spotlight#43]
### Reproduction steps

N/A

### Expected Results

Each contributor page has opengraph metadata set to ensure the profile picture, summary and background fit nicely independant of the site embedding a post.

### Actual Results

Due to the lack of opengraph metadata, thumbnails are treated differently depending on your browser.

**Comment by krisstern** [comment]
@kmartens27 Any suggestions as to what to include for the opengraph metadata?

**Comment by kmartens27** [comment]
@krisstern I'm not really sure what we could include in this case. Would adding opengraph:title: to the title help in this case? It seems that the current title is a level 1 heading on the page, so maybe that set of attributes could be adjusted to include opengraph data?

@NotMyFault, when you say the thumbnails are treated differently based on browser, would you be able to provide an example or screenshots showing the discrepancy?

**Comment by krisstern** [comment]
Hi @kmartens27,
We could say for example add open graph images to each page: https://www.gatsbyjs.com/plugins/gatsby-plugin-open-graph-images/. Alternatively, we could use a more advanced plugin to generate something called the social cards for sharing on social media: https://www.gatsbyjs.com/plugins/gatsby-plugin-social-cards/. I prefer the first approach, as it looks simpler and we could add description to the open graph metadata as well.
