### ISSUE TITLE
Fix missing svg icon of collapsed menu bar for mobile

### ISSUE THREAD

**Issue by sridamul** [jenkins-infra/contributor-spotlight#53]
### Reproduction steps

Open [contributor spotlight](https://contributors.jenkins.io/) page in mobile

### Expected Results

Expected to have the svg icon

![side bar icon](https://github.com/jenkins-infra/contributor-spotlight/assets/107404972/63ccd8a7-d4d7-4f02-ac7b-3ea4b117a95f)

### Actual Results

missing svg icon in the contributor spotlight page

![icon-missing](https://github.com/jenkins-infra/contributor-spotlight/assets/107404972/47eb7a2b-5c0b-4514-8c86-c1026a0d4009)

**Comment by sridamul** [comment]
@krisstern Can I resolve this issue?

**Comment by krisstern** [comment]
Hi @sridamul I have a feeling this issue belongs to https://github.com/jenkins-infra/jenkins-io-components. Maybe you should open an issus there instead.

**Comment by sridamul** [comment]
Hey @krisstern, I've noticed that the SVG icons are displaying correctly in other tabs, but there seems to be an issue specifically with the contributor spotlight tab. I've raised the problem here to address and resolve it.

**Comment by krisstern** [comment]
Thanks for reporting this @sridamul, we are still setting up the repo for others to contribute to it later so as I said before at least once to you we would like to take more **ownership** of this repo before it is ready for contributions from outside. So for the time being I will take care of the issue if you are very sure it is an issue solely on our side.
